/*coolie 1414141653894*/
define("Banner.js",["1"],function(){o.destroy();o=null}});
define("1",["2","3","4","5","6","7","8","9"],function(e,n){l.css(n,{width:"",height:"","float":""})});l.css(e._ele,{width:"",height:"",left:""});o.remove(e._nav);o.unwrap(e._ele,"div")}},h),p=".alien-ui-banner-nav{position:absolute;right:10px;bottom:10px;overflow:hidden;background:rgba(0, 0, 0, 0.33);padding:6px 12px;border-radius:4px}"+".alien-ui-banner-nav-item{display:inline-block;width:10px;height:10px;line-height:10px;padding:0;margin:0 6px;text-align:center;background:#666;cursor:default}"+".alien-ui-banner-nav-item-active{background:#fff}"+".alien-ui-banner-nav-text .alien-ui-banner-nav-item{width:auto;height:20px;line-height:22px;font-size:12px;font-weight:normal;color:#EEE;padding:0 6px}"+".alien-ui-banner-nav-text .alien-ui-banner-nav-item-active{color:#000}"+".alien-ui-banner-nav-square .alien-ui-banner-nav-item{}"+".alien-ui-banner-nav-circle .alien-ui-banner-nav-item{border-radius:100%}"+".alien-ui-banner-nav-transparent{background:transparent}"+".alien-ui-banner-nav-transparent .alien-ui-banner-nav-item{background:transparent;color:#999}"+".alien-ui-banner-nav-transparent .alien-ui-banner-nav-item-active{color:#fff;font-weight:900}";o.importStyle(p);t.exports=v});
define("2",["a","5","8"],function(){var e=h>d?l>0?"right":"left":u>0?"down":"up";c.extend(v.swipe.event,t,{direction:e});c.extend(v["swipe"+e].event,t);c.dispatch(f,v.swipe.event);c.dispatch(f,v["swipe"+e].event)},0)}});c.on(document,m,i);c.on(window,"scroll",i);n.exports=c});
define("a",["8","4"],function(e,t,n){var i=e[v];t=String(t).trim();if(!t)return 0;return n?(l&&l[i]&&l[i][t]||[]).length:(c&&c[i]&&c[i][t]||[]).length}}});
define("8",[],function(e,t){return Object.prototype.hasOwnProperty.call(e,t)}}});
define("4",["8","b"],function(e,i){if(t.call(i))n.push(i)});return n}}});
define("b",["8"],function(i,a){t=a?a+"-"+e:e;var o=p[t]?p[t]:t;if(r(o)in d.style){n=!0;return!1}});return n?t:null}}});
define("5",["8","b","4"],function(){return c("height",arguments)}}});
define("3",["8","4","5"],function(e){var t=this.create("style");e=String(e);this.insert(t,c,"beforeend");if(void 0!==t.styleSheet)t.styleSheet.cssText+=e;else t.appendChild(this.create("#text",e))}}});
define("6",["5","8","c","b","a"],function"!==o.type(h[3]))s=d;t=t||{};t.x=t.x===i?p.x:t.x;t.y=t.y===i?p.y:t.y;n=o.extend(!0,{},l,n);u={x:t.x-p.x,y:t.y-p.y};if(!u.x&&!u.y)return s.call(e);setTimeout(c,n.delay)}}});
define("c",[],function(e){return Math.sqrt(Math.sqrt(e))}}}});
define("7",["8"],function(e,t){var n=this,r=i.type(e);if("string"===r||"number"===r)return n._options[e]=t;else if("object"===r)i.extend(n._options,e)};return e.constructor}}});
define("9",["8","7"],function(e,i){if(i.apply(n,o)===!1)t=!1})});return t}});n.exports=a});