define(function () {
    var tinymce = window.tinymce;

    tinymce.addI18n('zh_CN', {
        "Cut": "剪切",
        "Header 1": "一级标题",
        "Heading 1": "一级标题",
        "Heading 2": "二级标题",
        "Header 2": "二级标题",
        "Header 3": "三级标题",
        "Heading 3": "三级标题",
        "Header 4": "四级标题",
        "Heading 4": "四级标题",
        "Heading 5": "五级标题",
        "Header 5": "五级标题",
        "Header 6": "六级标题",
        "Heading 6": "五级标题",
        "Pre": "预格式文本",
        "Preformatted": "预格式文本",
        "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.": "您的浏览器不支持剪贴板操作，请使用 CTRL+C/V 来操作。",
        "Div": "DIV区块",
        "Paste": "粘贴",
        "Close": "关闭",
        "Font Family": "字体",
        "Decrease indent": "减少缩进",
        "Align center": "居中",
        "Align right": "右对齐",
        "New document": "新文档",
        "Blockquote": "引用",
        "Numbered list": "编号列表",
        "Headings": "标题",
        "Increase indent": "增加缩进",
        "Formats": "格式",
        "Headers": "标题",
        "Select all": "全选",
        "Blocks": "区块",
        "Undo": "撤消",
        "Strikethrough": "删除线",
        "Bullet list": "项目符号",
        "Superscript": "上标",
        "Clear formatting": "清除格式",
        "Font Sizes": "字号",
        "Subscript": "下标",
        "Redo": "重复",
        "Paragraph": "段落",
        "Ok": "确定",
        "Bold": "粗体",
        "Code": "代码",
        "Italic": "斜体",
        "Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "当前为纯文本粘贴模式，再次点击可以回到普通粘贴模式。",
        "Underline": "下划线",
        "Cancel": "取消",
        "Justify": "两端对齐",
        "Inline": "文本",
        "Copy": "复制",
        "Align left": "左对齐",
        "Visual aids": "网格线",
        "Lower Greek": "小写希腊字母",
        "Square": "方块",
        "Default": "默认",
        "Lower Alpha": "小写英文字母",
        "Circle": "空心圆",
        "Disc": "实心圆",
        "Upper Alpha": "大写英文字母",
        "Upper Roman": "大写罗马字母",
        "Lower Roman": "小写罗马字母",
        "Name": "名称",
        "Anchor": "锚点",
        "You have unsaved changes are you sure you want to navigate away?": "你还有文档尚未保存，确定要离开？",
        "Restore last draft": "恢复上次的草稿",
        "Special character": "特殊符号",
        "Source code": "源代码",
        "Color": "颜色",
        "Right to left": "从右到左",
        "Left to right": "从左到右",
        "Emoticons": "表情",
        "Robots": "机器人",
        "Document properties": "文档属性",
        "Title": "标题",
        "Keywords": "关键词",
        "Encoding": "编码",
        "Description": "描述",
        "Author": "作者",
        "Fullscreen": "全屏",
        "Horizontal line": "水平分割线",
        "Horizontal space": "水平边距",
        "Insert/edit image": "插入/编辑图片",
        "General": "普通",
        "Advanced": "高级",
        "Source": "地址",
        "Border": "边框",
        "Constrain proportions": "保持宽高比",
        "Vertical space": "垂直边距",
        "Image description": "图片描述",
        "Style": "样式",
        "Dimensions": "大小",
        "Insert image": "插入图片",
        "Insert date/time": "插入日期/时间",
        "Remove link": "删除链接",
        "Url": "地址",
        "Text to display": "显示文字",
        "Anchors": "锚点",
        "Insert link": "插入链接",
        "New window": "在新窗口打开",
        "None": "无",
        "The URL you entered seems to be an external link. Do you want to add the required http:// prefix?": "你所填写的URL地址属于外部链接，需要加上 http://: 前缀吗？",
        "Target": "打开方式",
        "The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "你所填写的URL地址貌似是邮件地址，需要加上 mailto: 前缀吗？",
        "Insert/edit link": "插入/编辑链接",
        "Insert/edit video": "插入/编辑视频",
        "Poster": "封面",
        "Alternative source": "镜像",
        "Paste your embed code below:": "将内嵌代码粘贴在下面：",
        "Insert video": "插入视频",
        "Embed": "内嵌",
        "Nonbreaking space": "不间断空格",
        "Page break": "分页符",
        "Paste as text": "粘贴为文本",
        "Preview": "预览",
        "Print": "打印",
        "Save": "保存",
        "Could not find the specified string.": "未找到搜索内容",
        "Replace": "替换",
        "Next": "下一个",
        "Whole words": "全字匹配",
        "Find and replace": "查找和替换",
        "Replace with": "替换为",
        "Find": "查找",
        "Replace all": "全部替换",
        "Match case": "区分大小写",
        "Prev": "上一个",
        "Spellcheck": "拼写检查",
        "Finish": "完成",
        "Ignore all": "全部忽略",
        "Ignore": "忽略",
        "Add to Dictionary": "添加到字典",
        "Insert row before": "在上方插入",
        "Rows": "行",
        "Height": "高",
        "Paste row after": "粘贴到下方",
        "Alignment": "对齐方式",
        "Border color": "边框颜色",
        "Column group": "列组",
        "Row": "行",
        "Insert column before": "在左侧插入",
        "Split cell": "拆分单元格",
        "Cell padding": "单元格内边距",
        "Cell spacing": "单元格外间距",
        "Row type": "行类型",
        "Insert table": "插入表格",
        "Body": "表体",
        "Caption": "标题",
        "Footer": "表尾",
        "Delete row": "删除行",
        "Paste row before": "粘贴到上方",
        "Scope": "范围",
        "Delete table": "删除表格",
        "H Align": "水平对齐",
        "Top": "顶部对齐",
        "Header cell": "表头单元格",
        "Column": "列",
        "Row group": "行组",
        "Cell": "单元格",
        "Middle": "垂直居中",
        "Cell type": "单元格类型",
        "Copy row": "复制行",
        "Row properties": "行属性",
        "Table properties": "表格属性",
        "Bottom": "底部对齐",
        "V Align": "垂直对齐",
        "Header": "表头",
        "Right": "右对齐",
        "Insert column after": "在右侧插入",
        "Cols": "列",
        "Insert row after": "在下方插入",
        "Width": "宽",
        "Cell properties": "单元格属性",
        "Left": "左对齐",
        "Cut row": "剪切行",
        "Delete column": "删除列",
        "Center": "居中",
        "Merge cells": "合并单元格",
        "Insert template": "插入模板",
        "Templates": "模板",
        "Background color": "背景色",
        "Custom...": "自定义...",
        "Custom color": "自定义颜色",
        "No color": "无",
        "Text color": "文字颜色",
        "Show blocks": "显示区块边框",
        "Show invisible characters": "显示不可见字符",
        "Words: {0}": "字数：{0}",
        "Insert": "插入",
        "File": "文件",
        "Edit": "编辑",
        "Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "在编辑区按 ALT+F9 打开菜单，按 ALT+F10 打开工具栏，按 ALT+0 查看帮助",
        "Tools": "工具",
        "View": "视图",
        "Table": "表格",
        "Format": "格式"
    });
});


